#if !canImport(ObjectiveC)
import XCTest

extension TestsPerformance {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestsPerformance = [
        ("testExample", testExample),
        ("testPerformanceExample", testPerformanceExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TestsPerformance.__allTests__TestsPerformance),
    ]
}
#endif
